import {
  defineObject,
  FieldType,
  MetadataWritability,
  NumberDataType,
  OnDeleteAction,
  RelationType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
} from 'twenty-sdk/define';

import { DOCUMENT_STATUS_OPTIONS } from 'src/constants/document-status-options';
import {
  ASSINAFY_ACCOUNT_ID_FIELD_UNIVERSAL_IDENTIFIER,
  ASSINAFY_ASSIGNMENT_ID_FIELD_UNIVERSAL_IDENTIFIER,
  ASSINAFY_DOCUMENT_ID_FIELD_UNIVERSAL_IDENTIFIER,
  ASSINAFY_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
  COMPANY_ASSINAFY_DOCUMENTS_FIELD_UNIVERSAL_IDENTIFIER,
  COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
  COMPLETED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  DECLINE_REASON_FIELD_UNIVERSAL_IDENTIFIER,
  EXPIRES_AT_FIELD_UNIVERSAL_IDENTIFIER,
  LAST_ERROR_FIELD_UNIVERSAL_IDENTIFIER,
  LAST_SYNCED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  NAME_FIELD_UNIVERSAL_IDENTIFIER,
  OPPORTUNITY_ASSINAFY_DOCUMENTS_FIELD_UNIVERSAL_IDENTIFIER,
  OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
  PERSON_ASSINAFY_DOCUMENTS_FIELD_UNIVERSAL_IDENTIFIER,
  PERSON_FIELD_UNIVERSAL_IDENTIFIER,
  REQUEST_ID_FIELD_UNIVERSAL_IDENTIFIER,
  SENT_AT_FIELD_UNIVERSAL_IDENTIFIER,
  SIGNED_COUNT_FIELD_UNIVERSAL_IDENTIFIER,
  SIGNED_DOCUMENT_FIELD_UNIVERSAL_IDENTIFIER,
  SIGNER_COUNT_FIELD_UNIVERSAL_IDENTIFIER,
  SIGNERS_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

const APP_ONLY = MetadataWritability.APPLICATION;

export default defineObject({
  universalIdentifier: ASSINAFY_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'assinafyDocument',
  namePlural: 'assinafyDocuments',
  labelSingular: 'Documento Assinafy',
  labelPlural: 'Documentos Assinafy',
  description: 'Um documento enviado para assinatura eletrônica com a Assinafy.',
  icon: 'IconSignature',
  isUICreatable: false,
  labelIdentifierFieldMetadataUniversalIdentifier: NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Nome',
      description: 'Nome do documento exibido aos signatários.',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Status da assinatura, sincronizado com a Assinafy.',
      icon: 'IconProgressCheck',
      writability: APP_ONLY,
      options: DOCUMENT_STATUS_OPTIONS,
    },
    {
      universalIdentifier: ASSINAFY_DOCUMENT_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'assinafyDocumentId',
      label: 'ID do documento na Assinafy',
      icon: 'IconHash',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: ASSINAFY_ACCOUNT_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'assinafyAccountId',
      label: 'ID do workspace na Assinafy',
      icon: 'IconBuildingCommunity',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: ASSINAFY_ASSIGNMENT_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'assinafyAssignmentId',
      label: 'ID da solicitação na Assinafy',
      icon: 'IconHash',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: REQUEST_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'requestId',
      label: 'ID do envio',
      description: 'Chave de idempotência da tentativa de envio.',
      icon: 'IconKey',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: TEMPLATE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'templateName',
      label: 'Modelo',
      description: 'Modelo da Assinafy usado para criar o documento, se houver.',
      icon: 'IconTemplate',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: SIGNER_COUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'signerCount',
      label: 'Signatários',
      icon: 'IconUsers',
      writability: APP_ONLY,
      isAuditLogged: false,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: SIGNED_COUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'signedCount',
      label: 'Assinados',
      icon: 'IconUserCheck',
      writability: APP_ONLY,
      isAuditLogged: false,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: SIGNERS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RAW_JSON,
      name: 'signers',
      label: 'Detalhes dos signatários',
      description: 'Andamento dos signatários informado pela Assinafy.',
      icon: 'IconUsers',
      writability: APP_ONLY,
      isAuditLogged: false,
    },
    {
      universalIdentifier: SENT_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'sentAt',
      label: 'Enviado em',
      icon: 'IconSend',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: COMPLETED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'completedAt',
      label: 'Concluído em',
      icon: 'IconCircleCheck',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: EXPIRES_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'expiresAt',
      label: 'Prazo para assinar',
      icon: 'IconCalendarDue',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: LAST_SYNCED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'lastSyncedAt',
      label: 'Última verificação',
      icon: 'IconRefresh',
      writability: APP_ONLY,
      isAuditLogged: false,
    },
    {
      universalIdentifier: DECLINE_REASON_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'declineReason',
      label: 'Motivo da recusa',
      icon: 'IconMessageX',
      writability: APP_ONLY,
    },
    {
      universalIdentifier: LAST_ERROR_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'lastError',
      label: 'Último erro',
      description: 'Código da última operação com falha neste documento.',
      icon: 'IconAlertTriangle',
      writability: APP_ONLY,
      isAuditLogged: false,
    },
    {
      universalIdentifier: SIGNED_DOCUMENT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.FILES,
      name: 'signedDocument',
      label: 'Documento assinado',
      description: 'PDF certificado e, quando um certificado digital for usado, o PDF com certificado ICP-Brasil.',
      icon: 'IconFileCheck',
      writability: APP_ONLY,
      universalSettings: { maxNumberOfValues: 2 },
    },
    {
      universalIdentifier: PERSON_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'person',
      label: 'Pessoa',
      icon: 'IconUser',
      writability: APP_ONLY,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        PERSON_ASSINAFY_DOCUMENTS_FIELD_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'personId',
      },
    },
    {
      universalIdentifier: COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'company',
      label: 'Empresa',
      icon: 'IconBuildingSkyscraper',
      writability: APP_ONLY,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.company.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        COMPANY_ASSINAFY_DOCUMENTS_FIELD_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    {
      universalIdentifier: OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'opportunity',
      label: 'Oportunidade',
      icon: 'IconTargetArrow',
      writability: APP_ONLY,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.opportunity.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        OPPORTUNITY_ASSINAFY_DOCUMENTS_FIELD_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'opportunityId',
      },
    },
  ],
});
