import { defineView, getFieldUniversalIdentifier, ViewSortDirection } from 'twenty-sdk/define';

import {
  APPLICATION_UNIVERSAL_IDENTIFIER,
  ASSINAFY_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
  COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
  COMPLETED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_COMPLETED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_PERSON_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_SENT_AT_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_DEFAULT_SORT_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_SIGNED_COUNT_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_SIGNED_DOCUMENT_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_SIGNER_COUNT_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  DOCUMENTS_VIEW_UNIVERSAL_IDENTIFIER,
  NAME_FIELD_UNIVERSAL_IDENTIFIER,
  OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
  PERSON_FIELD_UNIVERSAL_IDENTIFIER,
  SENT_AT_FIELD_UNIVERSAL_IDENTIFIER,
  SIGNED_COUNT_FIELD_UNIVERSAL_IDENTIFIER,
  SIGNED_DOCUMENT_FIELD_UNIVERSAL_IDENTIFIER,
  SIGNER_COUNT_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

const COLUMNS: Array<[viewFieldUniversalIdentifier: string, fieldUniversalIdentifier: string, size: number]> = [
  [DOCUMENTS_VIEW_NAME_FIELD_UNIVERSAL_IDENTIFIER, NAME_FIELD_UNIVERSAL_IDENTIFIER, 240],
  [DOCUMENTS_VIEW_STATUS_FIELD_UNIVERSAL_IDENTIFIER, STATUS_FIELD_UNIVERSAL_IDENTIFIER, 170],
  [DOCUMENTS_VIEW_SIGNED_COUNT_FIELD_UNIVERSAL_IDENTIFIER, SIGNED_COUNT_FIELD_UNIVERSAL_IDENTIFIER, 100],
  [DOCUMENTS_VIEW_SIGNER_COUNT_FIELD_UNIVERSAL_IDENTIFIER, SIGNER_COUNT_FIELD_UNIVERSAL_IDENTIFIER, 100],
  [DOCUMENTS_VIEW_SENT_AT_FIELD_UNIVERSAL_IDENTIFIER, SENT_AT_FIELD_UNIVERSAL_IDENTIFIER, 160],
  [DOCUMENTS_VIEW_COMPLETED_AT_FIELD_UNIVERSAL_IDENTIFIER, COMPLETED_AT_FIELD_UNIVERSAL_IDENTIFIER, 160],
  [DOCUMENTS_VIEW_SIGNED_DOCUMENT_FIELD_UNIVERSAL_IDENTIFIER, SIGNED_DOCUMENT_FIELD_UNIVERSAL_IDENTIFIER, 200],
  [DOCUMENTS_VIEW_PERSON_FIELD_UNIVERSAL_IDENTIFIER, PERSON_FIELD_UNIVERSAL_IDENTIFIER, 180],
  [DOCUMENTS_VIEW_COMPANY_FIELD_UNIVERSAL_IDENTIFIER, COMPANY_FIELD_UNIVERSAL_IDENTIFIER, 180],
  [DOCUMENTS_VIEW_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER, OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER, 180],
];

export default defineView({
  universalIdentifier: DOCUMENTS_VIEW_UNIVERSAL_IDENTIFIER,
  name: 'Documentos Assinafy',
  objectUniversalIdentifier: ASSINAFY_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
  icon: 'IconSignature',
  position: 0,
  fields: COLUMNS.map(([universalIdentifier, fieldMetadataUniversalIdentifier, size], position) => ({
    universalIdentifier,
    fieldMetadataUniversalIdentifier,
    position,
    size,
    isVisible: true,
  })),
  // Newest first by creation, like the Assinaturas tab: records never sent (Enviando, Falhou, Confira na Assinafy) have
  // no sentAt and would sink to the end.
  sorts: [
    {
      universalIdentifier: DOCUMENTS_VIEW_DEFAULT_SORT_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier: getFieldUniversalIdentifier({
        applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
        objectUniversalIdentifier: ASSINAFY_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
        name: 'createdAt',
      }),
      direction: ViewSortDirection.DESC,
    },
  ],
});
